# Generated by Django 3.0.7 on 2020-06-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('message_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('message_content', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('num_users', models.SmallIntegerField()),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='remotely.Channel_Member')),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='remotely.Message')),
            ],
        ),
    ]
